dependencies = []
description = "Go library which aims at syncing / copying one file tree to another in a clever way, a bit like rsync"
destination_server = []
flags = ["global"]
languages = ["go", "github-actions"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.0"
