dependencies = []
description = "Go library which aims at syncing / copying one file tree to another in a clever way, a bit like rsync"
destination_server = []
flags = ["global"]
languages = ["go"]
owner = "etienne@scalingo.com"
team = "IST"
version = "1.1.0"
